name: Build Arch Linux ISO with XFCE

on:
  workflow_dispatch:
    inputs:
      build_date:
        description: 'ISO build timestamp (YYYYMMDD_HHMMSS). Leave empty for current time.'
        required: false
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install archiso, tools & p7zip
        run: |
          pacman -Sy --noconfirm \
            archiso squashfs-tools xorriso dosfstools \
            p7zip curl util-linux binutils jq

      - name: Prepare XFCE profile
        id: prepare_profile
        shell: bash
        run: |
          PROFILE=xfce-profile
          rm -rf "$PROFILE"
          cp -r /usr/share/archiso/configs/releng "$PROFILE"

          mkdir -p \
            "$PROFILE/airootfs/root" \
            "$PROFILE/airootfs/etc/lightdm" \
            "$PROFILE/airootfs/etc/systemd/system/multi-user.target.wants"

          for pkg in \
            xfce4 xfce4-goodies xorg-server xorg-xinit \
            lightdm lightdm-gtk-greeter networkmanager \
            firefox htop iotop gparted network-manager-applet
          do
            echo "$pkg" >> "$PROFILE/packages.x86_64"
          done

          # Enable NetworkManager service on boot
          ln -s /usr/lib/systemd/system/NetworkManager.service \
            "$PROFILE/airootfs/etc/systemd/system/multi-user.target.wants/NetworkManager.service"          

          # Create nm-applet autostart file with echo
          mkdir -p "$PROFILE/airootfs/root/.config/autostart"
          AUTOSTART="$PROFILE/airootfs/root/.config/autostart/nm-applet.desktop"
          echo '[Desktop Entry]'                           > "$AUTOSTART"
          echo 'Type=Application'                         >> "$AUTOSTART"
          echo 'Name=Network Manager Applet'              >> "$AUTOSTART"
          echo 'Exec=nm-applet --indicator'               >> "$AUTOSTART"
          echo 'OnlyShowIn=XFCE;'                         >> "$AUTOSTART"
          echo 'Terminal=false'                           >> "$AUTOSTART"
          echo 'X-GNOME-Autostart-enabled=true'           >> "$AUTOSTART"

          sed -i \
            -e 's/^iso_name=.*/iso_name="archlinux-xfce"/' \
            -e 's/^iso_label=.*/iso_label="ARCH_XFCE"/' \
            "$PROFILE/profiledef.sh"
            
          # --- START OF ZSTD COMPRESSION MODIFICATIONS (Broken Down) ---
          # Step 1: Change the compression algorithm from 'xz' to 'zstd'
          # and explicitly set a faster compression level (e.g., 3).
          # This replaces '-comp' 'xz' with '-comp' 'zstd' '-Xcompression-level' '5'.
          # We use '|' as the sed delimiter to avoid issues with '/' in file paths or text.
          sed -i "s|'-comp' 'xz'|'-comp' 'zstd' '-Xcompression-level' '5'|" "$PROFILE/profiledef.sh"

          # Step 2: Remove the xz-specific BCJ filter.
          # This removes the '-Xbcj' 'x86' part which is not used by zstd.
          sed -i "s|'-Xbcj' 'x86'||" "$PROFILE/profiledef.sh"

          # Step 3: Remove the xz-specific dictionary size option.
          # This removes the '-Xdict-size' '1M' part which is also not used by zstd.
          sed -i "s|'-Xdict-size' '1M'||" "$PROFILE/profiledef.sh"
          # --- END OF ZSTD COMPRESSION MODIFICATIONS (Broken Down) ---
        
          curl -fsSL \
            https://raw.githubusercontent.com/georgeabr/arch/refs/heads/master/arch.sh \
            -o "$PROFILE/airootfs/root/arch.sh"
          chmod +x "$PROFILE/airootfs/root/arch.sh"

          # Ensure it'll stay executable on first login shell (TTY auto-login)
          echo 'chmod +x /root/arch.sh' \
            >> "$PROFILE/airootfs/root/.bash_profile"


          echo 'root:x:0:0:root:/root:/bin/bash' \
            > "$PROFILE/airootfs/etc/passwd"

          echo 'exec startxfce4' \
            > "$PROFILE/airootfs/root/.xinitrc"

          echo '[Seat:*]' \
            > "$PROFILE/airootfs/etc/lightdm/lightdm.conf"
          echo 'autologin-user=root' \
            >> "$PROFILE/airootfs/etc/lightdm/lightdm.conf"
          echo 'autologin-session=xfce' \
            >> "$PROFILE/airootfs/etc/lightdm/lightdm.conf"

          # Set console keymap & font
          mkdir -p "$PROFILE/airootfs/etc"
          echo "KEYMAP=uk"    > "$PROFILE/airootfs/etc/vconsole.conf"
          echo "XKBLAYOUT=gb" >> "$PROFILE/airootfs/etc/vconsole.conf"
          echo "FONT=ter-922b" >> "$PROFILE/airootfs/etc/vconsole.conf"

          # Enable NetworkManager applet autostart in XFCE
          mkdir -p "$PROFILE/airootfs/root/.config/autostart"

          echo "profile_dir=$PROFILE" >> "$GITHUB_OUTPUT"

      - name: Verify profiledef.sh contents
        shell: bash
        run: |
          echo "--- Contents of ${{ steps.prepare_profile.outputs.profile_dir }}/profiledef.sh ---"
          cat "${{ steps.prepare_profile.outputs.profile_dir }}/profiledef.sh"
          echo "---------------------------------------------------------"

      - name: Determine build timestamp
        id: ts
        shell: bash
        run: |
          BUILD_TS="${{ github.event.inputs.build_date }}"
          [ -z "$BUILD_TS" ] && BUILD_TS=$(date '+%Y%m%d_%H%M%S')
          echo "build_timestamp=$BUILD_TS" >> "$GITHUB_OUTPUT"

      - name: Build the ISO
        id: build_iso
        shell: bash
        run: |
          OUT=out
          mkarchiso -v -o "$OUT" "${{ steps.prepare_profile.outputs.profile_dir }}"
          ISO=$(find "$OUT" -maxdepth 1 -type f -name '*.iso' -print -quit)
          [ -z "$ISO" ] && { echo "ERROR: ISO not found!" >&2; exit 1; }
          echo "iso_path=$ISO" >> "$GITHUB_OUTPUT"

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-xfce-iso-${{ steps.ts.outputs.build_timestamp }}
          path: ${{ steps.build_iso.outputs.iso_path }}

      - name: Fetch latest kernel version from Arch repo
        id: fetch_kernel
        shell: bash
        run: |
          PKG_JSON=$(curl -fsSL 'https://archlinux.org/packages/core/x86_64/linux/json/')
          PKGVER=$(echo "$PKG_JSON" | jq -r '.pkgver')
          PKGREL=$(echo "$PKG_JSON" | jq -r '.pkgrel')
          echo "KERNEL_VERSION_REPO=${PKGVER}-${PKGREL}" >> "$GITHUB_OUTPUT"


      - name: Create GitHub Release (Optional)
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ steps.build_iso.outputs.iso_path }}
          tag_name: "iso-${{ steps.ts.outputs.build_timestamp }}"
          name: "Arch Linux XFCE ISO ${{ steps.ts.outputs.build_timestamp }}"
          body: |
            Arch Linux ISO built on ${{ steps.ts.outputs.build_timestamp }}
            using the `xfce-profile`.
            Includes the `arch.sh` script in `/root/arch.sh`.
            Root user's default shell set to `/bin/bash`.
            Includes `htop`, `iotop`, `mc`, `gparted`.
            Based on Arch Linux packages available at build time.
            Kernel version (from Arch repo): `${{ steps.fetch_kernel.outputs.KERNEL_VERSION_REPO }}`
            Use `startx` to launch XFCE.
            From a terminal, use `./arch.sh` to start the installation.
            Installation is logged to a timestamped file like `install-20250418_1431.log`.
          prerelease: false
