name: Build Custom Arch Linux ISO with arch.sh script

on:
  workflow_dispatch:
    inputs:
      build_date:
        description: 'ISO Build Timestamp (YYYYMMDD_HHMMSS, leave empty for current time)'
        required: false
        type: string
      profile_name:
        description: 'Name of the archiso profile to use (e.g., "releng" or your custom profile folder)'
        required: false
        type: string
        default: 'releng'

# ADDED: Permissions block for creating releases
permissions:
  contents: write # This grants permission to create and edit releases

jobs:
  build_iso:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged

    timeout-minutes: 120

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install archiso and build dependencies within the container
      run: |
        pacman -Sy --noconfirm archiso git squashfs-tools xorriso dosfstools curl

    - name: Prepare Archiso Build Profile and Add Custom Script
      id: prepare_profile
      run: |
        PROFILE_DIR="archiso_build_profile"
        INPUT_PROFILE_NAME="${{ github.event.inputs.profile_name }}"
        SCRIPT_URL="https://raw.githubusercontent.com/georgeabr/arch/refs/heads/master/arch.sh"
        SCRIPT_FILENAME="arch.sh"
        SCRIPT_DEST_PATH="$PROFILE_DIR/airootfs/root/$SCRIPT_FILENAME"

        if [ -d "./$INPUT_PROFILE_NAME" ]; then
          echo "Using custom profile from repository: ./$INPUT_PROFILE_NAME"
          cp -r "./$INPUT_PROFILE_NAME" "$PROFILE_DIR"
        elif [ -d "/usr/share/archiso/configs/$INPUT_PROFILE_NAME" ]; then
          echo "Using official archiso profile: /usr/share/archiso/configs/$INPUT_PROFILE_NAME"
          cp -r "/usr/share/archiso/configs/$INPUT_PROFILE_NAME" "$PROFILE_DIR"
        else
          echo "Error: Profile '$INPUT_PROFILE_NAME' not found in repository or official configs."
          exit 1
        fi

        mkdir -p "$(dirname "$SCRIPT_DEST_PATH")"
        echo "Downloading $SCRIPT_URL to $SCRIPT_DEST_PATH"
        curl -sSL "$SCRIPT_URL" -o "$SCRIPT_DEST_PATH"
        echo "Setting executable permissions for $SCRIPT_DEST_PATH"
        chmod +x "$SCRIPT_DEST_PATH"

        echo "PROFILE_DIR=$PROFILE_DIR" >> "$GITHUB_OUTPUT"

    - name: Define Build Metadata and Output Directory
      id: build_metadata
      shell: bash
      run: |
        # Use user-provided build_date if available, otherwise generate current timestamp
        if [ -n "${{ github.event.inputs.build_date }}" ]; then
          BUILD_TIMESTAMP="${{ github.event.inputs.build_date }}"
        else
          BUILD_TIMESTAMP=$(date '+%Y%m%d_%H%M%S')
        fi

        ISO_VERSION_IDENTIFIER="${GITHUB_REF_NAME:-$(echo $GITHUB_SHA | cut -c1-7)}"
        ISO_OUTPUT_DIR="out" # Directory where mkarchiso will place the ISO

        echo "BUILD_TIMESTAMP=$BUILD_TIMESTAMP" >> "$GITHUB_OUTPUT"
        echo "ISO_VERSION_IDENTIFIER=$ISO_VERSION_IDENTIFIER" >> "$GITHUB_OUTPUT"
        echo "ISO_OUTPUT_DIR=$ISO_OUTPUT_DIR" >> "$GITHUB_OUTPUT"

    - name: Build Arch Linux ISO
      id: build_iso_step # Add ID to capture output from this step
      run: |
        mkarchiso -v -o ${{ steps.build_metadata.outputs.ISO_OUTPUT_DIR }} ${{ steps.prepare_profile.outputs.PROFILE_DIR }}/
        
        # FIND THE ACTUAL GENERATED ISO FILENAME
        ACTUAL_ISO_FILE=$(find ${{ steps.build_metadata.outputs.ISO_OUTPUT_DIR }} -name "*.iso" -print -quit)
        if [ -z "$ACTUAL_ISO_FILE" ]; then
          echo "Error: No ISO file found in ${{ steps.build_metadata.outputs.ISO_OUTPUT_DIR }}"
          exit 1
        fi
        echo "Found ISO: $ACTUAL_ISO_FILE"
        echo "ACTUAL_ISO_FILE=$ACTUAL_ISO_FILE" >> "$GITHUB_OUTPUT"

    - name: List generated ISOs (for debugging)
      run: ls -lh ${{ steps.build_metadata.outputs.ISO_OUTPUT_DIR }}

    - name: Upload ISO as Artifact
      uses: actions/upload-artifact@v4
      with:
        # Use the actual file found in the previous step
        name: archlinux-custom-iso-${{ steps.build_metadata.outputs.BUILD_TIMESTAMP }}
        path: ${{ steps.build_iso_step.outputs.ACTUAL_ISO_FILE }}
        retention-days: 7

    - name: Create GitHub Release (Optional)
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        # Use the actual file found in the build step
        files: ${{ steps.build_iso_step.outputs.ACTUAL_ISO_FILE }}
        # Use the generated timestamp for a clean tag and name
        tag_name: "iso-${{ steps.build_metadata.outputs.BUILD_TIMESTAMP }}"
        name: "Arch Linux Custom ISO ${{ steps.build_metadata.outputs.BUILD_TIMESTAMP }}"
        body: |
          Custom Arch Linux ISO built on ${{ steps.build_metadata.outputs.BUILD_TIMESTAMP }}
          using the ${{ github.event.inputs.profile_name }} archiso profile.
          Includes the 'arch.sh' script in /root/arch.sh.
          Based on Arch Linux packages available at build time.
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
