name: Build Arch Linux ISO with XFCE

on:
  workflow_dispatch:
    inputs:
      build_date:
        description: 'ISO build timestamp (YYYYMMDD_HHMMSS). Leave empty for current time.'
        required: false
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install archiso and tools
        run: |
          pacman -Sy --noconfirm \
            archiso squashfs-tools xorriso dosfstools \
            curl util-linux

      - name: Prepare XFCE profile
        id: prepare_profile
        shell: bash
        run: |
          PROFILE=xfce-profile
          rm -rf "$PROFILE"
          cp -r /usr/share/archiso/configs/releng "$PROFILE"

          # Ensure necessary directories
          mkdir -p \
            "$PROFILE/airootfs/root" \
            "$PROFILE/airootfs/etc/lightdm" \
            "$PROFILE/airootfs/etc/systemd/system/multi-user.target.wants"

          # Append XFCE & utilities
          for pkg in \
            xfce4 xfce4-goodies xorg-server xorg-xinit \
            lightdm lightdm-gtk-greeter networkmanager \
            firefox htop iotop gparted
          do
            echo "$pkg" >> "$PROFILE/packages.x86_64"
          done

          # Patch ISO metadata
          sed -i \
            -e 's/^iso_name=.*/iso_name="archlinux-xfce"/' \
            -e 's/^iso_label=.*/iso_label="ARCH_XFCE"/' \
            -e 's/^iso_publisher=.*/iso_publisher="Arch Linux XFCE Custom"/' \
            -e 's/^iso_application=.*/iso_application="Arch Linux XFCE Live ISO"/' \
            "$PROFILE/profiledef.sh"

          # Inject your custom script
          curl -fsSL \
            https://raw.githubusercontent.com/georgeabr/arch/refs/heads/master/arch.sh \
            -o "$PROFILE/airootfs/root/arch.sh"
          chmod +x "$PROFILE/airootfs/root/arch.sh"

          # Ensure root uses bash
          echo 'root:x:0:0:root:/root:/bin/bash' \
            > "$PROFILE/airootfs/etc/passwd"

          # Auto-start XFCE for root
          echo 'exec startxfce4' \
            > "$PROFILE/airootfs/root/.xinitrc"

          # Configure LightDM for root autologin
          echo '[Seat:*]' \
            > "$PROFILE/airootfs/etc/lightdm/lightdm.conf"
          echo 'autologin-user=root' \
            >> "$PROFILE/airootfs/etc/lightdm/lightdm.conf"
          echo 'autologin-session=xfce' \
            >> "$PROFILE/airootfs/etc/lightdm/lightdm.conf"

          # Export profile path
          echo "profile_dir=$PROFILE" >> "$GITHUB_OUTPUT"

      - name: Determine build timestamp
        id: ts
        shell: bash
        run: |
          TS="${{ github.event.inputs.build_date }}"
          [ -z "$TS" ] && TS=$(date '+%Y%m%d_%H%M%S')
          echo "build_timestamp=$TS" >> "$GITHUB_OUTPUT"

      - name: Build the ISO
        id: build_iso
        shell: bash
        run: |
          OUT=out
          mkarchiso -v -o "$OUT" "${{ steps.prepare_profile.outputs.profile_dir }}"
          ISO=$(find "$OUT" -maxdepth 1 -type f -name '*.iso' -print -quit)
          if [ -z "$ISO" ]; then
            echo "ERROR: ISO not found!" >&2
            exit 1
          fi
          echo "iso_path=$ISO" >> "$GITHUB_OUTPUT"

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-xfce-iso-${{ steps.ts.outputs.build_timestamp }}
          path: ${{ steps.build_iso.outputs.iso_path }}
