# .github/workflows/trizen.yml

name: Build trizen-git Arch Package

# allow this workflow to create releases via GITHUB_TOKEN
permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install base-devel, git & sudo
        run: |
          pacman -Sy --noconfirm --needed
          pacman -S --noconfirm --needed base-devel git sudo

      - name: Create non-root builder user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder
          chmod 440 /etc/sudoers.d/builder
          chown -R builder:builder "$GITHUB_WORKSPACE"

      - name: Clone Trizen AUR repo as builder
        run: |
          sudo -E -u builder bash -lc \
            "git clone https://aur.archlinux.org/trizen.git \"$GITHUB_WORKSPACE/trizen\""

      - name: Build the Arch package as builder
        id: pkg_build
        run: |
          sudo -E -u builder bash -lc \
            "cd \"$GITHUB_WORKSPACE/trizen\" && \
             MAKEFLAGS=\"-j$(nproc)\" \
             makepkg --noconfirm --syncdeps --rmdeps --skippgpcheck -f"

      - name: Gather built package
        run: |
          mkdir -p "$GITHUB_WORKSPACE/artifacts"
          mv "$GITHUB_WORKSPACE/trizen"/*.pkg.tar.zst "$GITHUB_WORKSPACE/artifacts/"

      - name: Generate build metadata
        id: build_meta
        run: |
          echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >>"$GITHUB_OUTPUT"
          echo "architecture=$(uname -m)"                   >>"$GITHUB_OUTPUT"

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          # If you want to release on an existing tag, pass it here.
          # Otherwise this will create a release named by the run number.
          tag_name: ${{ github.ref_name || format('run-{0}', github.run_number) }}
          name: trizen ${{ github.ref_name || format('run-{0}', github.run_number) }}
          body: |
            Package:      trizen-git for Arch Linux
            Built on:     ${{ steps.build_meta.outputs.build_date }}
            Architecture: ${{ steps.build_meta.outputs.architecture }}
          files: artifacts/*.pkg.tar.zst
        env:
          # GITHUB_TOKEN with `contents: write` permission (set above)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
